const menu = [
  {
    id: 1,
    title: "Abacha",
    category: "breakfast",
    price: 2000,
    img: "./food/item-1.jpeg",
    desc: `Lorem, ipsum dolor sit amet consectetur adipisicing elit. Culpa aperiam ipsa, magni deserunt necessitatibus fuga.`,
  },
  {
    id: 2,
    title: "afang soup and starch",
    category: "lunch",
    price: 2000,
    img: "./food/item-2.jpeg",
    desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Illo magnam vero eligendi id maxime omnis!`,
  },
  {
    id: 3,
    title: "amala and ewedu",
    category: "lunch",
    price: 1000,
    img: "./food/item-3.jpeg",
    desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Magnam, corrupti.`,
  },
  {
    id: 4,
    title: "asun",
    category: "dinner",
    price: 2000,
    img: "./food/item-4.jpg",
    desc: `Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatibus, porro.`,
  },
  {
    id: 5,
    title: "beans, yam and plantain",
    category: "lunch",
    price: 500,
    img: "./food/item-5.jpeg",
    desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam, quasi?`,
  },
  {
    id: 6,
    title: "boli and fish",
    category: "dinner",
    price: 1500,
    img: "./food/item-6.jpeg",
    desc: `Lorem ipsum dolor sit amet consectetur, adipisicing elit. Aperiam, aspernatur!`,
  },
  {
    id: 7,
    title: "boli and fish with pepper sauce",
    category: "lunch",
    price: 1500,
    img: "./food/item-7.jpeg",
    desc: `Lorem ipsum dolor sit amet consectetur, adipisicing elit. At, ullam.`,
  },
  {
    id: 8,
    title: "bread and beans",
    category: "lunch",
    price: 400,
    img: "./food/item-8.jpeg",
    desc: `Lorem ipsum, dolor sit amet consectetur adipisicing elit. Earum, corrupti.`,
  },
  {
    id: 9,
    title: "cat fish pepper soup",
    category: "dinner",
    price: 2000,
    img: "./food/item-9.jpeg",
    desc: `Lorem ipsum dolor sit amet, consectetur adipisicing elit. Libero, nobis!`,
  },
  {
    id: 10,
    title: "cheese",
    category: "dinner",
    price: 2000,
    img: "./food/item-10.jpeg",
    desc: `Lorem, ipsum dolor sit amet consectetur adipisicing elit. Omnis, magni.`,
  },
  {
    id: 11,
    title: "dodo and chicken",
    category: "dinner",
    price: 1500,
    img: "./food/item-11.jpeg",
    desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. In, sed?`,
  },
  {
    id: 12,
    title: "fried rice",
    category: "lunch",
    price: 2000,
    img: "./food/item-12.jpeg",
    desc: `Lorem ipsum dolor sit, amet consectetur adipisicing elit. Velit, optio.`,
  },
  {
    id: 13,
    title: "gizdodo",
    category: "dinner",
    price: 1500,
    img: "./food/item-13.jpg",
    desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem, assumenda.`,
  },
  {
    id: 14,
    title: "goat meat pepper soup",
    category: "dinner",
    price: 2500,
    img: "./food/item-14.jpeg",
    desc: `Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum, nihil?`,
  },
  {
    id: 15,
    title: "ikubobi",
    category: "dinner",
    price: 2000,
    img: "./food/item-15.jpeg",
    desc: `Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dicta, aliquam.`,
  },
  {
    id: 16,
    title: "isiewu",
    category: "dinner",
    price: 2000,
    img: "./food/item-16.jpeg",
    desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur, consectetur.`,
  },
  {
    id: 17,
    title: "jollof rice",
    category: "lunch",
    price: 2000,
    img: "./food/item-17.jpeg",
    desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt, maxime!`,
  },
  {
    id: 18,
    title: "ogi and akara",
    category: "breakfast",
    price: 400,
    img: "./food/item-18.jpeg",
    desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam, facilis.`,
  },
  {
    id: 19,
    title: "ogi and moimoi",
    category: "breakfast",
    price: 600,
    img: "./food/item-19.jpeg",
    desc: `Lorem, ipsum dolor sit amet consectetur adipisicing elit. Laboriosam, ad!`,
  },
  {
    id: 20,
    title: "plantain porrigde",
    category: "lunch",
    price: 1000,
    img: "./food/item-20.jpeg",
    desc: `Lorem, ipsum dolor sit amet consectetur adipisicing elit. Numquam, optio!`,
  },
  {
    id: 21,
    title: "yam porrigde",
    category: "lunch",
    price: 600,
    img: "./food/item-21.jpeg",
    desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum, amet?`,
  },
  {
    id: 22,
    title: "coconut rice",
    category: "lunch",
    price: 1500,
    img: "./food/item-22.jpeg",
    desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quis, suscipit.`,
  },
  {
    id: 23,
    title: "salad chicken",
    category: "breakfast",
    price: 1000,
    img: "./food/item-23.jpeg",
    desc: `Lorem ipsum dolor sit amet, consectetur adipisicing elit. Numquam, dolores!`,
  },
  {
    id: 24,
    title: "semo and egusi",
    category: "lunch",
    price: 900,
    img: "./food/item-24.jpeg",
    desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam, explicabo?`,
  },
  {
    id: 25,
    title: "stick meat",
    category: "dinner",
    price: 800,
    img: "./food/item-25.jpeg",
    desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Labore, ratione.`,
  },
  {
    id: 26,
    title: "starch and white soup",
    category: "lunch",
    price: 1000,
    img: "./food/item-26.jpeg",
    desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, impedit.`,
  },
  {
    id: 27,
    title: "suya",
    category: "dinner",
    price: 1000,
    img: "./food/item-27.jpeg",
    desc: `Lorem ipsum, dolor sit amet consectetur adipisicing elit. Impedit, placeat?`,
  },
  {
    id: 28,
    title: "unriped plantain porrigde",
    category: "lunch",
    price: 1000,
    img: "./food/item-28.jpeg",
    desc: `Lorem ipsum, dolor sit amet consectetur adipisicing elit. Placeat, quia!`,
  },
  {
    id: 29,
    title: "yamarita",
    category: "breakfast",
    price: 700,
    img: "./food/item-29.jpg",
    desc: `Lorem ipsum dolor sit amet consectetur, adipisicing elit. Error, sapiente.`,
  },
  {
    id: 30,
    title: "yam and egg",
    category: "breakfast",
    price: 500,
    img: "./food/item-30.jpeg",
    desc: `Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ipsam, atque?`,
  },
];

export default menu;
